import type { Metadata } from "next";
import { Suspense } from "react";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { UserProvider } from "./context/UserContext";
import OnboardingGuard from "./components/OnboardingGuard";
import RouteWarmup from "./components/RouteWarmup";

const geistSans = Noto_Sans_Thai({
  weight: "500",
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.className}`}>
        <UserProvider>
          <RouteWarmup />
          <OnboardingGuard />
          <Suspense
            fallback={
              <header className="h-16 w-full border-b border-zinc-200 bg-white" aria-hidden />
            }
          >
            <Navbar />
          </Suspense>
          {children}
        </UserProvider>
        <Footer />
      </body>
    </html>
  );
}
