import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapClient from "./components/BootstrapClient";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Noto_Sans_Thai({
  weight: "500",
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.className}`}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <BootstrapClient />
      </body>
    </html>
  );
}
